import type { Metadata } from 'next';
import { Inter, Outfit, Lobster } from 'next/font/google';
import './globals.css';

import AuthProvider from '../components/AuthProvider';
import Navbar from '../components/Navbar';
import QueryProvider from '../components/QueryProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });
const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  weight: '400',
});

const lobster = Lobster({
  subsets: ['latin'],
  variable: '--font-lobster',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lobster.variable} ${outfit.variable}`}>
        <AuthProvider>
          <QueryProvider>
            <Navbar />
            <div className="pt-[120px] sm:pt-[70px] mx-2">
              {children}
              <ToastContainer
                position="bottom-right"
                theme="dark"
                autoClose={2000}
              />
            </div>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
