import type { Metadata } from 'next';
import { Inter, Roboto, Smooch_Sans, Rubik_Bubbles } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import Navbar from '@/components/Navbar';
import QueryProvider from '@/components/QueryProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });
const smooch_sans = Smooch_Sans({
  subsets: ['latin'],
  variable: '--font-smooch_sans',
  weight: '400',
});

const rubik_bubbles = Rubik_Bubbles({
  subsets: ['latin'],
  variable: '--font-rubik_bubbles',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik_bubbles.variable}`}>
        <AuthProvider>
          <QueryProvider>
            <Navbar />
            <div className="pt-[120px] sm:pt-[70px] mx-2">
              {children}
              <ToastContainer
                position="bottom-right"
                theme="dark"
                autoClose={2000}
              />
            </div>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
